# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popularity99', models.FloatField()),
                ('director', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('imdb_score', models.FloatField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
